<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public function queryCommentsPerNews($newsId, $limit)
    {
        return $this
            ->createQueryBuilder('c')
            ->leftJoin('c.news', 'news')
            ->andWhere('news.id = :newsid')
            ->setParameter('newsid', $newsId)
            ->setMaxResults($limit)
            ->orderBy('c.published', 'DESC')
            ->getQuery()->getResult();
    }

    public function queryCommentsAll()
    {
        return $this
            ->createQueryBuilder('c')
            ->leftJoin('c.news', 'news')
            ->orderBy('c.published', 'DESC')
            ->getQuery()->getResult();
    }
}












